required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x: -153.410
  y: 70.50000
  z: 218.452
  yaw: 0
  pitch: 0
arenas:
  0:
    world: 'world'
    x: -153.417
    y: 71.50000
    z: 203.356
    yaw: 0
    pitch: 0
  1:
    world: 'world'
    x: -153.484
    y: 71.50000
    z: 194.385
    yaw: 0
    pitch: 0